import { EXCEL_TYPES } from './app.constant';

export const bulkUploadDataMap = {
  [EXCEL_TYPES.COUNTRY]: ['name'],
  [EXCEL_TYPES.STATE]: ['name', 'zone'],
  [EXCEL_TYPES.ZONE]: ['name'],
  [EXCEL_TYPES.CITY]: ['name', 'state'],
  [EXCEL_TYPES.CLUSTER]: ['name', 'state'],
  [EXCEL_TYPES.PIN_CODE]: ['pin', 'area', 'city'],
  [EXCEL_TYPES.USER_ROLE]: ['name', 'description'],
  [EXCEL_TYPES.USER]: [
    'parentId',
    'email',
    'firstName',
    'lastName',
    'mobile',
    'gender',
    'highestQualification',
    'role',
  ],
  [EXCEL_TYPES.POC_TYPE]: ['name'],
  [EXCEL_TYPES.PERSON_OF_CONTACT]: [
    'name',
    'pocType',
    'mobile',
    'email',
    'address',
    'designation',
    'client',
  ],
  [EXCEL_TYPES.CLIENT]: ['name', 'company', 'industry', 'logo', 'size'],
  [EXCEL_TYPES.INDUSTRY]: ['name'],
  [EXCEL_TYPES.IFSC]: ['code', 'bank'],
  [EXCEL_TYPES.EMPLOYMENT_TYPE]: ['name'],
  [EXCEL_TYPES.DESIGNATION]: ['name'],
  [EXCEL_TYPES.DEPARTMENT]: ['name'],
  [EXCEL_TYPES.COMPANY]: ['name', 'industry', 'logo'],
  [EXCEL_TYPES.BANK]: ['name'],
  [EXCEL_TYPES.ATTENDANCE]: ['present', 'absenceReason', 'date', 'user'],
};
