export enum CLIENT_DOCUMENTS_TYPE {
  AGREEMENT = 'AGREEMENT',
  GST = 'GST',
  ADDENDUM = 'ADDENDUM',
  TDS_CERTIFICATE = 'TDS_CERTIFICATE',
}

export const CLIENT_DOCUMENTS_LIST = Object.keys(CLIENT_DOCUMENTS_TYPE);
